# Generated by Django 5.2.6 on 2025-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('album_art_url', models.URLField(blank=True, max_length=500, null=True)),
                ('artists', models.ManyToManyField(related_name='tracks', to='spotifyapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyProfile',
            fields=[
                ('spotify_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('top_artists', models.ManyToManyField(related_name='profiles_top_artists', to='spotifyapp.artist')),
                ('top_tracks', models.ManyToManyField(related_name='profiles_top_tracks', to='spotifyapp.track')),
            ],
        ),
    ]
